baseURL = 'https://blog.claude.nl/'
languageCode = 'en-uk'
title = 'BYOC'
theme = 'ConciseShortStyle'

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup]
  _merge = "deep"

[params]
    custom_css = ["scss/custom.scss"]
  [params.comments.giscus]
    enabled = 1
    repo = "reinhrst/website.claude.nl"
    repo-id = "R_kgDOGpOc7Q"
    category = "Giscus"
    category-id = "DIC_kwDOGpOc7c4CWO_y"
    mapping = "pathname"
    strict = "1"
    reactions-enabled = "1"
    emit-metadata = "0"
    input-position = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

  [params.analytics.getinsights]
    enabled = 1
    tracking_id = "h1khfarqCIVoXjwC"

  [params.footer]
      hugo = false
      copyright = false
      author = true
      license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    

[menu]
  [[menu.main]]
    identifier = "About"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "Privacy"
    pre = ""
    post = ""
    name = "Privacy"
    url = "/about/"
    title = ""
    weight = 3

[frontmatter]
  date = ['date', ':filename', ':default']
  publishDate = ['publishDate', 'date', ':filename', ':default']

