baseURL = 'https://blog.claude.nl/'
languageCode = 'en-uk'
title = 'BYOC'
theme = 'ConciseShortStyle'

[markup]
  _merge = "deep"

[params]
    custom_css = ["scss/custom.scss"]
  [params.comments.giscus]
    enabled = 1
    repo = "reinhrst/website.claude.nl"
    data-repo-id = "R_kgDOGpOc7Q"
    data-category = "Giscus"
    data-category-id = "DIC_kwDOGpOc7c4CWO_y"
    mapping = "pathname"
    strict = "1"
    reactions-enabled = "1"
    emit-metadata = "1"
    input-position = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

  [params.analytics.getinsights]
    enabled = 1
    tracking_id = "h1khfarqCIVoXjwC"

  [params.footer]
      hugo = false
      copyright = false
      author = true
      license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

[frontmatter]
  date = ['date', ':filename', ':default']
  publishDate = ['publishDate', 'date', ':filename', ':default']

